### ISSUE TITLE
Able to sync the Wishlist?

### ISSUE THREAD

**Issue by profucius** [Jeshibu/PlayniteExtensions#21]
I keep my wishlisted games within Playnite by using the Completion field to store a "Wishlist" value. It would be really nice to be able to sync the Wishlist to/from RAWG, since your addon syncs other categories, and RAWG offers Wishlist as a categorization.  Is this possible?

**Comment by Jeshibu** [comment]
Done in 0.3.1

**Comment by Jeshibu** [comment]
The first point works on my end. I've got 2 games in my wishlist, and when I run `main menu > Update game library > RAWG` they get imported with the status I selected.
Check the plugin settings - you might have Wishlist set to "Do not import"

As for the second, updating game completion status to the RAWG status is not a feature (yet?) outside of newly imported games from the RAWG library.

**Comment by profucius** [comment]
Thanks. I'll do some testing following your instructions. If I still cant get it to work, I'll record some evidence and create a new ticket for it, since this one is correctly closed.
